### PR TITLE
Add signal translation tests

### PR DESCRIPTION
**Pull request by chriskuehl**
@mcclurmc added a couple tests and some minor tweaks. How does this look to you?

### CODE REVIEW

**Comment by asottile** [comment]
Would it be possible to use this to ignore signals?  (Might be useful)

**Comment by chriskuehl** [comment]
@asottile we could pretty easily make it so that rewriting to zero (or similar) was equivalent to ignore. I'd be in favor of that (but maybe we should do it after merging this PR?).

**Comment by asottile** [comment]
Sounds good with me :)

**Comment by mcclurmc** [comment]
@chriskuehl This looks awesome, thanks for cleaning up my code and adding tests!

**Pull request merged**
